name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm run test -- --forceExit
      
    - name: Build extension
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-build
        path: dist/

  ios-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS dependencies
      run: |
        cd platforms/ios
        xcodebuild -resolvePackageDependencies
        
    - name: Build iOS project
      run: |
        cd platforms/ios
        xcodebuild build -scheme HistoryTracker -destination 'platform=iOS Simulator,name=iPhone 14'
        
    - name: Run iOS tests
      run: |
        cd platforms/ios
        xcodebuild test -scheme HistoryTracker -destination 'platform=iOS Simulator,name=iPhone 14'